name: aufgabe2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '21'

          - name: Checkout repository
            uses: actions/checkout@v4

          - name: run maven
            run: mvn -B clean verify
    
